security:

    encoders:
        App\Entity\User:
            algorithm: bcrypt
            cost: 12

    providers:
        db_provider:
            entity:
                class: App\Entity\User

    firewalls:

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: true
            lazy: true

            guard:
                authenticators:
                    - App\Security\Admin\LoginFormAuthenticator

            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800
                path:     /

            form_login:
                login_path: admin login
                check_path: admin login
                csrf_token_generator: security.csrf.token_manager
                default_target_path: admin locations
                always_use_default_target_path: true
                failure_path: admin login

            logout:
                path: admin logout
                target: admin login

    access_control:
        - { path: ^/(admin|en/admin)/login , roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(admin|en/admin), roles: ROLE_ADMIN }